<?php

namespace Cimetiere\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CimetiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CimetiereRepository extends EntityRepository {

    public function findCarte($data) {

        $qb = $this->createQueryBuilder('a');
        if ($data != NULL) {
            $qb->andWhere('a.nomCimetiere LIKE :data')->setParameter('data', '%' . $data . '%');
        }
        return $qb->getQuery()->getResult();
    }
    
     public function findCodeCimetiere() {

        $qb = $this->createQueryBuilder('a')
        ->select('a.codeCimetiere');
        return $qb->getQuery()->getResult();
    }

    public function listeNomCimetiere($term) {
        $qb = $this->createQueryBuilder('c');

        $qb->select('c.nomCimetiere')
                ->where('c.nomCimetiere LIKE :term1 OR c.nomCimetiere LIKE :term2 OR c.nomCimetiere LIKE :term3')
                ->setParameter('term1', '%'.$term)
                ->setParameter('term2', $term . '%')
                ->setParameter('term3', '%' . $term . '%');
        $arrayAss = $qb->getQuery()
                ->getArrayResult();

        // Transformer le tableau associatif en un tableau standard
        $array = array();
        foreach ($arrayAss as $data) {
            $array[] = $data['nomCimetiere'];
        }

        return $array;
    }
    
    public function listeCodeCimetiere($term) {
        $qb = $this->createQueryBuilder('c');

        $qb->select('c.codeCimetiere')
                ->where('c.codeCimetiere LIKE :term1 OR c.codeCimetiere LIKE :term2 OR c.codeCimetiere LIKE :term3')
                ->setParameter('term1', '%'.$term)
                ->setParameter('term2', $term . '%')
                ->setParameter('term3', '%' . $term . '%');
        $arrayAss = $qb->getQuery()
                ->getArrayResult();

        // Transformer le tableau associatif en un tableau standard
        $array = array();
        foreach ($arrayAss as $data) {
            $array[] = $data['codeCimetiere'];
        }

        return $array;
    }
    
    public function findEntities($codeCimetiere, $nomCimetiere){
         $qb = $this->createQueryBuilder('c');
        if ($codeCimetiere != NULL) {
            $qb->andWhere('c.codeCimetiere LIKE :data')->setParameter('data', '%' . $codeCimetiere . '%');
        }
        if ($nomCimetiere != NULL) {
            $qb->andWhere('c.nomCimetiere LIKE :data')->setParameter('data', '%' . $nomCimetiere . '%');
        }
        return $qb->getQuery()->getResult();
    }

} 