<?php

namespace Cimetiere\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DefuntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefuntRepository extends EntityRepository
{
}
