<?php

namespace Cimetiere\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RechercheCarte*Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RechercheCarteRepository extends EntityRepository
{
}
