parameters:
#    cimetiere.example.class: Cimetiere\Bundle\Example

services:
#    cimetiere.example:
#        class: %cimetiere.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
